### ISSUE TITLE
Move to monorepo

### ISSUE THREAD

**Issue by camacho** [camacho/format-package#65]
Per the conversation in issue #61, we should consider moving to a monorepo.

@peterkc had a [proposal](https://github.com/camacho/format-package/issues/61#issuecomment-516833770) that could serve as a good foundation.

I would also like to move [`sort-scripts`](https://github.com/camacho/sort-scripts) into the monorepo.

I think this could be a good approach. I also own a few namespaces on npm that could help - `@format-package`, `@format-packages`, `@formatter`, `@packagejson`, `@pkgjson`. Not sure if we want to approach this in that fashion, but there are at least options.

I'd like to use Yarn workspaces and Lerna to manage the repo, if possible. Thoughts and recommendations for setup?

**Comment by revelt** [comment]
I have managed to set up a monorepo, although slightly different stack: npm (not yarn), Lerna (frozen in time at 3.13.0 because of https://github.com/lerna/lerna/issues/2117), GitLab CI for publishing to npm upon `git push`, no Typescript, but with Rollup.

Also, I code in slightly unconventional way where I keep full package logging with copious `console.log`'s, each reporting line numbers — sources are in ES6 — Rollup removes comments and console.log's and produces ES6 (with `import`), CJS (with `require`) and UMD builds (for websites, with all dependencies baked in, then minified).

Monorepo setup does require some new tooling which I had to write myself: 

[update-versions](https://www.npmjs.com/package/update-versions) because [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) won't do deep updates, plus the former puts versions of existing local packages even if they are older and newer exist on npm ("bastardised" packages). It's an essential tool you run daily.

[lerna-clean-changelogs-cli](https://www.npmjs.com/package/lerna-clean-changelogs-cli) because maintenance with `upd` (above) will require continuous dependency bumping, and not everytime there will be features to mention in changelog. Normally, automated releases generate rubbish changelog entries and this program removes those. This CLI is ran on CI.

[lerna-link-dep](https://www.npmjs.com/package/lerna-link-dep) used to add a dependency, another package from a monorepo. It scans monorepo for a CLI or normal package of that name and creates symlinks Lerna-style for it, pointing to the requested package. Normally, you'd manually update `package.json`, wipe all dependencies `lerna wipe` and `lerna bootstrap` from scratch. Latter way requires internet, takes 1 minute and requires you to manually look up exact version of that local monorepo package, OR put whatever and run `upd` (see # 1, which in turn takes time). There are plans to put `pacote` on it and enable to add any package from npm if it does not exist on monorepo.

[lect](https://www.npmjs.com/package/lect) — daily maintenance of 99 packages would be impossible without it — it's poorly documented quasi-internal maintenance CLI. It does:
* updates readme, in philosophy of readme-as-template, "in-place" as opposed to standalone config and untouchable faceless readme (famous https://github.com/verbose/verb-generate-readme)
* generates `.npmignore` with global and local whitelist/blacklist and awareness of local monorepo package's files/folders, `lect` will ask about new file/folder names and update whitelist/blacklist and `.npmignore`.
* enforces eslintrc consistent for each package, no safely escape latches at local config (in-file comments are used)
* generates full Rollup config file from scratch, with tricks in a sleeve to bypass `console.log`/JS comment removal upon `--dev`/`-d` flag to allow daily development
* enforces dependencies, npm scripts by two categories: normal package or a CLI. Former need more, latter need less. There are escape latches to allow ad-hoc dependencies
* other per-package, `package.json`-driven operations like deleting ad-hoc files or dependencies (handy for migration)

plus, I maintain bastardised ava myself (https://gitlab.com/codsen/codsen/tree/master/packages/ava) frozen at 2.2.5 — with extras like since-patched monorepo support, TS-cruft removed and most importantly, `t.only` and test file isolation when magic string is present in test file — `ava` is on `esm` and `nyc` and coverage is manually written to the readme badge each time `nyc` tests are ran.

plus, `prettier`, ESLint driven using `eslint-config-prettier`, as opposed to standalone prettier CLI setup

plus, `commitizen` and `cz-conventional-changelog`

plus, home-brewn perf checking using `benchmark` with historical perf database per-each-non-CLI-package (see https://gitlab.com/codsen/codsen/tree/master/packages/email-comb/perf), ran on each full package's `npm test`

---

sources:
https://gitlab.com/codsen/codsen
https://gitlab.com/codsen/codsen/blob/master/.gitlab-ci.yml

In practice, it took me whole Christmas Dec 2018, all 2 week holidays, pretty much coding full-time, one accidental major semver bump and npm-publish on all monorepo packages existing at that time (~70) and ten or so blank patch semver bumps while backwards-engineering poorly-documented Lerna and GitLab CI.

---

With regards to question on #61,

> Would this deter you @peterkc (or anyone else) from contributing?

I think TS is a bad idea and will cause unsolvable problems down the line. I'd bet, problems will arise in ava-Babel-ES6-esm-nyc and/or Rollup areas, and especially in the way of comment-driven development where `console.log`s are kept in the program source. I tried to add documentation on https://github.com/fb55/domutils/ before it was migrated to TS. After migration, it became impossible to add any `console.log`s — `tsc` removed all logs and broke my `console.log`-driven development. `tsc` enforces you to use browser or VSCode-based debug tools. Neither of two ways is good nor bad, I just can't work any other way. It seems I'm more productive than browser or VSCode-based debug tool users — 

---

PS.  I spent an hour writing this up as a gratitude to @camacho for this program. I still use it besides `prettier` to enforce peace and order in my packages.

**Comment by camacho** [comment]
@revelt wow! This is an amazingly thorough and well thought out proposal/explanation of putting together a monorepo at an enormous scale. The infrastructure and problems you have dealt with are more than anything I've ever had to consider. 

Thank you for sharing this knowledge and your advice on how we should best approach this topic, and for doing so in a respectful manner, even when there is disagreement. There is a lot of information here that I need to continue to digest, but my first thoughts:

1. I have had similar experiences about needing to roll my own software to support monrepos at previous companies who had large problems like this. It is always hard to maintain and adds an additional overhead but also an additional barrier for new contributors. Sometimes, though, it just can't be avoided.
1. The problems your custom packages solve are the type of problems I worry about all the time. A lot of the community has solved these problems for individual packages, but not for monorepos. My previous solutions have attempted to use globs or other types of collection of packages to be fed through the single project tools, one-by-one. Your solutions approaching the problem as a collection of projects alleviates this.
1. The other technologies around commits, compiling/transpiling, etc. are near and dear to my heart <3. I am a huge tools nerd and it reads like you are, too! We will absolutely be keeping that type of tooling around (I'm not sure what form, though).
1. And, lastly, I do not agree with your assessment of TypeScript and will be electing to using it on this project and enforce its use (I am not sure what level). I am writing this as a recent convert, having strongly hated working in both Flow and TypeScript in the past. Today, I simply could not imagine writing without it and I don't want to build this repo with cross project dependencies without the type knowledge.

I hope the last point doesn't turn you off from using this project going forward. And I hope we can collaborate together so you could share your expertise with us and help make the project better for everyone. Your time and knowledge are already a significant contribution.

**Comment by revelt** [comment]
👍🏻

**Comment by camacho** [comment]
@revelt can I tag you on PRs related to this issue so we can collaborate?

**Comment by revelt** [comment]
@camacho sure! I'll help all I can.

**Comment by camacho** [comment]
Stale - might revisit in the future
